/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import Controlador.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import Modelo.*;

/**
 *
 * @author Elizabeth
 */
public class clienteVista extends javax.swing.JFrame {

    Cliente cliente1 = new Cliente();
    CRUD operaciones = new CRUD();

    /**
     * Creates new form cliente
     */
    public clienteVista() {
        initComponents();
        llamar_clientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_limpiar = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jlbl_cedula = new javax.swing.JLabel();
        jlbl_nombre = new javax.swing.JLabel();
        jlbl_apellido = new javax.swing.JLabel();
        jlbl_direccion = new javax.swing.JLabel();
        jlbl_telefono = new javax.swing.JLabel();
        jlbl_pais = new javax.swing.JLabel();
        jlbl_correo = new javax.swing.JLabel();
        jlbl_contacto = new javax.swing.JLabel();
        jtxt_nombre = new javax.swing.JTextField();
        jtxt_cedula = new javax.swing.JTextField();
        jtxt_apellido = new javax.swing.JTextField();
        jtxt_direccion = new javax.swing.JTextField();
        jtxt_telefono = new javax.swing.JTextField();
        jtxt_pais = new javax.swing.JTextField();
        jtxt_correo = new javax.swing.JTextField();
        jtxt_contacto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_cliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_limpiar.setText("Limpiar");
        jbtn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarActionPerformed(evt);
            }
        });

        jbtn_guardar.setText("Guardar");
        jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarActionPerformed(evt);
            }
        });

        jbtn_actualizar.setText("Actualizar");
        jbtn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarActionPerformed(evt);
            }
        });

        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });

        jlbl_cedula.setText("Cédula");

        jlbl_nombre.setText("Nombre");

        jlbl_apellido.setText("Apellido");

        jlbl_direccion.setText("Dirección");

        jlbl_telefono.setText("Teléfono");

        jlbl_pais.setText("País");

        jlbl_correo.setText("Correo");

        jlbl_contacto.setText("Contacto de emergencia");

        jtxt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_nombreKeyTyped(evt);
            }
        });

        jtxt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cedulaKeyTyped(evt);
            }
        });

        jtxt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_apellidoKeyTyped(evt);
            }
        });

        jtxt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_telefonoKeyTyped(evt);
            }
        });

        jtxt_contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_contactoKeyTyped(evt);
            }
        });

        jtbl_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbl_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_cliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_limpiar)
                        .addGap(153, 153, 153)
                        .addComponent(jbtn_guardar))
                    .addComponent(jlbl_cedula)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_nombre)
                            .addComponent(jlbl_apellido)
                            .addComponent(jlbl_direccion)
                            .addComponent(jlbl_telefono)
                            .addComponent(jlbl_pais)
                            .addComponent(jlbl_correo)
                            .addComponent(jlbl_contacto))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_correo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_pais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_direccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jbtn_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_eliminar)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_cedula)
                    .addComponent(jtxt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_nombre)
                            .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_apellido)
                            .addComponent(jtxt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_direccion)
                            .addComponent(jtxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_telefono)
                            .addComponent(jtxt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_pais)
                            .addComponent(jtxt_pais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_correo)
                            .addComponent(jtxt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_contacto)
                    .addComponent(jtxt_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_limpiar)
                    .addComponent(jbtn_guardar)
                    .addComponent(jbtn_actualizar)
                    .addComponent(jbtn_eliminar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarActionPerformed
        // TODO add your handling code here:
        guardar_cliente();
        llamar_clientes();
    }//GEN-LAST:event_jbtn_guardarActionPerformed

    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed
        // TODO add your handling code here:
        eliminar_cliente();
        llamar_clientes();
    }//GEN-LAST:event_jbtn_eliminarActionPerformed

    private void jbtn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarActionPerformed
        // TODO add your handling code here:
        jtxt_cedula.setText(" ");
        jtxt_nombre.setText(" ");
        jtxt_apellido.setText(" ");
        jtxt_direccion.setText(" ");
        jtxt_telefono.setText(" ");
        jtxt_pais.setText(" ");
        jtxt_correo.setText(" ");
        jtxt_contacto.setText(" ");

    }//GEN-LAST:event_jbtn_limpiarActionPerformed

    private void jbtn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarActionPerformed
        // TODO add your handling code here:
        try {

            actualizar_cliente();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(clienteVista.class.getName()).log(Level.SEVERE, null, ex);
        }
        llamar_clientes();

    }//GEN-LAST:event_jbtn_actualizarActionPerformed

    private void jtbl_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_clienteMouseClicked
        // TODO add your handling code here:
        int fila = jtbl_cliente.getSelectedRow();

        jtxt_cedula.setText(jtbl_cliente.getValueAt(fila, 0).toString());
        jtxt_nombre.setText(jtbl_cliente.getValueAt(fila, 1).toString());
        jtxt_apellido.setText(jtbl_cliente.getValueAt(fila, 2).toString());
        jtxt_direccion.setText(jtbl_cliente.getValueAt(fila, 3).toString());
        jtxt_telefono.setText(jtbl_cliente.getValueAt(fila, 4).toString());
        jtxt_pais.setText(jtbl_cliente.getValueAt(fila, 5).toString());
        jtxt_correo.setText(jtbl_cliente.getValueAt(fila, 6).toString());
        jtxt_contacto.setText(jtbl_cliente.getValueAt(fila, 7).toString());

    }//GEN-LAST:event_jtbl_clienteMouseClicked

    private void jtxt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cedulaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Debe ingresar números", "ALERTA", 2);
        }

    }//GEN-LAST:event_jtxt_cedulaKeyTyped

    private void jtxt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_nombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Debe ingresar letras", "ALERTA", 2);
        }
    }//GEN-LAST:event_jtxt_nombreKeyTyped

    private void jtxt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_apellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Debe ingresar letras", "ALERTA", 2);
        }
    }//GEN-LAST:event_jtxt_apellidoKeyTyped

    private void jtxt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_telefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Debe ingresar números", "ALERTA", 2);
        }
    }//GEN-LAST:event_jtxt_telefonoKeyTyped

    private void jtxt_contactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_contactoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Debe ingresar números", "ALERTA", 2);
        }
    }//GEN-LAST:event_jtxt_contactoKeyTyped

    private void guardar_cliente() {
        int cedula = Integer.parseInt(jtxt_cedula.getText());
        String nombre = jtxt_nombre.getText();
        String apellido = jtxt_apellido.getText();
        String direccion = jtxt_direccion.getText();
        String telefono = jtxt_telefono.getText();
        String pais = jtxt_pais.getText();
        String correo = jtxt_correo.getText();
        String contacto = jtxt_contacto.getText();

        this.cliente1.setCedula(cedula);
        this.cliente1.setNombre(nombre);
        this.cliente1.setApellido(apellido);
        this.cliente1.setDireccion(direccion);
        this.cliente1.setTelefono(telefono);
        this.cliente1.setPais(pais);
        this.cliente1.setCorreo(correo);
        this.cliente1.setContacto(contacto);

        //  if(validar_unicidad_cedula_telefono()){
        // ejecutar try catch
        //}else{mensaje de error
        //  }
        try {
            this.operaciones.guardar_cliente(Conexion.obtener(), this.cliente1);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se ha podido guardar el registro.");
        }
    }

    public void llamar_clientes() {
        try {
            jtbl_cliente.setModel(operaciones.llamar_clientes(Conexion.obtener()));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ha surgido un error" + e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(clienteVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void eliminar_cliente() {
        int cedula = Integer.parseInt(jtxt_cedula.getText());
        try {
            this.operaciones.eliminar_por_codigo_cliente(Conexion.obtener(), cedula);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se ha podido guardar el registro.");
        }
    }

    public void actualizar_cliente() throws ClassNotFoundException {
        int cedula = Integer.parseInt(jtxt_cedula.getText());
        String nombre = jtxt_nombre.getText();
        String apellido = jtxt_apellido.getText();
        String direccion = jtxt_direccion.getText();
        String telefono = jtxt_telefono.getText();
        String pais = jtxt_pais.getText();
        String correo = jtxt_correo.getText();
        String contacto = jtxt_contacto.getText();

        System.out.println("ClienteVistaCodigo-- " + cedula);

        this.cliente1.setNombre(nombre);
        this.cliente1.setApellido(apellido);
        this.cliente1.setCedula(cedula);
        this.cliente1.setDireccion(direccion);
        this.cliente1.setTelefono(telefono);
      
        this.cliente1.setPais(pais);
        this.cliente1.setCorreo(correo);
        this.cliente1.setContacto(contacto);

        try {
            this.operaciones.actualizar_clientes(Conexion.obtener(), this.cliente1);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se ha podido guardar el registro.");
        }

    }

    /**
     * }
     * }
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clienteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_actualizar;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_guardar;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JLabel jlbl_apellido;
    private javax.swing.JLabel jlbl_cedula;
    private javax.swing.JLabel jlbl_contacto;
    private javax.swing.JLabel jlbl_correo;
    private javax.swing.JLabel jlbl_direccion;
    private javax.swing.JLabel jlbl_nombre;
    private javax.swing.JLabel jlbl_pais;
    private javax.swing.JLabel jlbl_telefono;
    private javax.swing.JTable jtbl_cliente;
    private javax.swing.JTextField jtxt_apellido;
    private javax.swing.JTextField jtxt_cedula;
    private javax.swing.JTextField jtxt_contacto;
    private javax.swing.JTextField jtxt_correo;
    private javax.swing.JTextField jtxt_direccion;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_pais;
    private javax.swing.JTextField jtxt_telefono;
    // End of variables declaration//GEN-END:variables
}
